{
  "hash": "f9079a4d1c138f1ad6d7df032203a232",
  "result": {
    "markdown": "---\ntitle: \"Lesson 20 take-home points\"\nauthor: \"Daniel Kaplan\"\ndate: \"2023-03-07\"\ncategories: [Class sessions, variance, DAGs, causality]\n---\n\n\n\n\n## Review\n\n1. Measure variation using the \"variance.\" In R, \n\n\n::: {.cell}\n\n```{.r .cell-code}\nGalton %>% summarize(vh = var(height))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       vh\n1 12.8373\n```\n:::\n:::\n\n    Interpretation: The heights of the people in the `Galton` data frame vary. The amount of this variability is the variance: 12.8 square-inches. In less strange units, the standard deviation is $\\sqrt{12.8 \\text{square-inches}} = 3.6$ inches\n\n2. The most common action for the rest of this course will be to **create a model** and **summarize** it.\n\n    Example: `lm(height ~ mother + father, data=Galton)`\n\n    - `height ~ mother + father` is a **tilde expression** that specifies the roles of variables in the model. `height` is the response variable. `mother` and `father` are the explanatory variables.\n    - `data = Galton` tells `lm()` to use the `Galton` data frame to construct the model corresponding to the tilde expression.\n        \n    Example: Summarizing functions `R2()` and `conf_interval()`\n    \n\n::: {.cell}\n\n```{.r .cell-code}\nlm(height ~ mother + father, data=Galton) |> R2()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    n k  Rsquared       F     adjR2 p df.num df.denom\n1 898 2 0.1088952 54.6856 0.1069039 0      2      895\n```\n:::\n:::\n\n\n    Interpretation: `mother` and `father` jointly explain about 10% of the variance in the `height` of their adult children.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(height ~ mother + father, data=Galton) |> conf_interval()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 4\n  term          .lwr  .coef   .upr\n  <chr>        <dbl>  <dbl>  <dbl>\n1 (Intercept) 13.9   22.3   30.8  \n2 mother       0.187  0.283  0.380\n3 father       0.290  0.380  0.470\n```\n:::\n:::\n\n\n    Interpretation: The model equation for a person's height in inches is, according to this model:\n\n$$\\text{person's height} = 22.3 + 0.283\\ \\mathtt{mother} + 0.380\\ \\mathtt{father}$$\n3. Regression models (such as those built by `lm()`) quantify how to account-for/explain the **variation** in the response variable in terms of the **variation** in the explanatory variables. \n\n## New topics\n\n4. Account-for/explain. Often when we use the word \"explain\" we mean to suggest a **causal** connection. For instance, [this randomized clinical trial](www/1-s2.0-S0140673697053816-main.pdf) established that a particular blood-pressure drug leads to lower blood pressure, that is, it *causes* the blood pressure to go down. \n\n5. When we say that \"A causes B,\" we don't necessarily mean that A is the complete and total explanation for B. More often, we mean that \"A contributes in some way to the value of B.\" For instance, \"high blood pressure increases mortality\" does not mean that high blood pressure is the sole determinant of mortality. Instead, it means that high blood pressure contributes to an increased risk of mortality.\n\n6. A **DAG** (Directed acyclic graph---unnecessarily intimidating name!) is a way of encoding a hypothesis of what causes what in a system. We discussed the system involving treating a battlefield casualty with a tourniquet. ([Link to in-class activity](https://dtkaplan.github.io/Math-300Z/Day-by-day/Lesson-20/Life-savers.html).) The system---a \"system\" is a collection of components---involved USE of a tourniquet, SEVERITY of injury, staying alive long enough for ADMISSION to hospital, and post-hospital SURVIVAL. Common sense suggests some **causal** connections:\n\n    i. SEVERITY $\\longrightarrow$ USE, since tourniquets are used for severe injuries involving bleeding from a limb.\n    ii. SEVERITY $\\longrightarrow$ ADMISSION. The more severe the injury, the less likely the soldier is to reach the hospital.\n    iii. ADMISSION $\\longrightarrow$ SURVIVAL. There would be little point to having hospitals if they didn't contribute to survival!\n    iv. SEVERITY $\\longrightarrow$ SURVIVAL. Even if reaching the hospital, the soldier's survival is in part determined by the SEVERITY of the injury.\n    \n    Other link were more hypothetical:\n    \n    v. USE $\\longrightarrow$ ADMISSION\n    vi. USE $\\longrightarrow$ SURVIVAL\n    \n7. A DAG describes the hypothesized causal links among all the system components.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n::: {.callout-note}\n## More detail\n\nThe [clinical study](https://www.annemergmed.com/article/S0196-0644(14)01408-5/fulltext) looking at the relationship between tourniquet use and survival included only those patients admitted to the hospital, not the ones who died before admission. Their data did not demonstration a relationship between USE and SURVIVAL. That is to say, the hypothesized DAG as a result of the study was this:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIn this second DAG, there is no causal connection between USE and SURVIVAL.\n\nA critique of the clinical trial is that it didn't consider ADMISSION, that is, both those soldiers who reached the hospital and those who didn't. Consequently, even if there were no direct link between USE and SURVIVAL, a more complete DAG includes a possible indirect path, as in this third DAG:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe path USE $\\longrightarrow$ ADMISSION $\\longrightarrow$ SURVIVAL could not be demonstrated by the (imperfect) clinical study, even though it might well exist. Any decision about the efficacy of tourniquets would need to consider the possible path USE $\\longrightarrow$ ADMISSION $\\longrightarrow$ SURVIVAL.\n\nHere's a *paradox*: Effective use of tourniquets *increases* hospital mortality rates. Explain why this says something positive about tourniquet use. \n\n:::\n\n## NOT gotten to in class\n\n1. Use of `sample()` and `dag_draw()` with DAGs.\n\n2. What is a \"random trial\"\n\n3. How (and why) to automate replication of random trials. \n\nYou can learn these things from the text and the worksheet for Lesson 20.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}