project:
  type: website
  output-dir: docs

website:
  title: "Math300 Blog"
  navbar:
    left:
      - href: "https://dtkaplan.github.io/Math-300Z/"
        text: "Spring 2023 class schedule"
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



