---
title: "Personality and Academic Performance"
author: "Daniel Kaplan"
date: "2023-11-08"
categories: [textbook example, prediction]
format:
  html:
    toc: true
---

```{r echo=FALSE}
source("../../Utils.R")
```

This post provides details of an example of predicting a quantitative outcome from *Lessons* 
`r LST_text_crossref("440-Predictions.html#form-of-statistical-prediction-quantitative-outcome", label="Chapter 22")`. The example concerns predicting a college student's overall grade-point average (GPA) from predictor variables that could be available at the time of an admissions decision. The example comes from a research paper:

Morgan N. McCredie, John E. Kurtz (2020)
"Prospective prediction of academic performance in college using self- and informant-rated personality traits",
*Journal of Research in Personality* **85** [DOI](https://doi.org/10.1016/j.jrp.2019.103911) and [link]((https://www.sciencedirect.com/science/article/pii/S009265661930131X)

> Abstract: Five-factor personality ratings were provided by undergraduate freshmen, their parents, and their college peers as predictors of cumulative GPA upon graduation. Conscientiousness ratings were significant predictors of GPA by all three raters; peer ratings of Conscientiousness were the only significant predictor of GPA when self-, parent-, and peer-ratings of Conscientiousness were examined simultaneously. College major was a moderator of this relationship, with self- and parent-ratings of Conscientiousness correlating more strongly with GPA among Social Science majors and parent-ratings of Conscientiousness correlating less strongly with GPA among Science majors. These findings replicate existing research regarding the validity of informant ratings as predictors of behavioral outcomes such as academic performance, while emphasizing the importance of including multiple informants from various life contexts.

The example is not intended as an endorsement or criticism of that research paper or its findings. Instead, the purpose is to highlight a statistical-thinking perspective on how to evaluate a prediction, including whether the prediction is suited for a given purpose.

The "Five-factor personality" traits are nicely summarized in Malcolm Gladwell's book *Blink* (p. 35): 

> 1. Extraversion. Are you sociable or retiring? Fun-loving or reserved? 
> 2. Agreeableness. Are you trusting or suspicious? Helpful or uncooperative?
> 3. Conscientiousness. Are you organized or disorganized? Self-disciplined or weak willed?
> 4. Emotional stability. Are you worried or calm? Insecure or secure?
> 5. Openness to new experiences. Are you imaginative or down-to-earth? Independent or conforming?

The work by McCredie & Kurtz established that the "conscientiousness" factor was, for non-science students, most strongly associated with GPA. In their study, they combined ratings of each trait from the different sources: the student's mother and father as well as a "peer" of the student. In the example in *Lessons*, for the sake of simplicity, only the mother's rating was used.
